### PR TITLE
Writing data to a file

### PR DESCRIPTION
**Pull request by bewils**
Hello, I have used this module to finish my homework but when I wanted to write data to a file I met some problems. The first problem is I don't know how to write data into a file. The document of js-xlsx only tells to use 'type' option to write but has no demo and after I read the codes of it I knew and then I add it to README. The other problem I have write it as commit in the code. Thanks for your module!

### CODE REVIEW

**Comment by marco-m-alves** [comment]
Was this really solved? I just got an error while trying

```
buffer.js:262
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
```

**Comment by satyasaadhak** [comment]
Is there a solution to this yet? Facing the same problem. I get the file buffer, but need to write that to a file.

**Comment by yspb** [comment]
import fs from 'fs'
import xlsx from 'node-xlsx'
const data = [[1, 2, 3], [true, false, null, 'sheetjs'], ['foo', 'bar', new Date('2014-02-19T14:30Z'), '0.3'], ['baz', null, 'qux']]
const buffer = xlsx.build([{ name: '', data: data }])
fs.writeFileSync(`data.xlsx`, buffer)

**Comment by huarse** [comment]
Why is closed ? I got the same problem

```ts
const buffer = xlsx.build([
    { name: 'sheet1', data: [['aa'], ['bb']]) },
  ]);

  fs.writeFileSync(resultFile, buffer, { flag: 'w' });
```

```
Argument of type 'ArrayBuffer' is not assignable to parameter of type 'string | Uint8Array | Uint8ClampedArray | Uint16Array | Uint32Array | Int8Array | Int16Array | ... 5 more ... | DataView'.
  Type 'ArrayBuffer' is missing the following properties from type 'Float64Array': BYTES_PER_ELEMENT, buffer, byteOffset, copyWithin, and 23 more.

134   fs.writeFileSync(resultFile, buffer, { flag: 'w' });
```

**Pull request closed without merging**
