### PR TITLE
feat: allow to pass a function to "range" option

### PR DESCRIPTION
**Pull request by vied12**
By default, `XLSX.utils.sheet_to_json` crops the data to the first not empty columns.

I was needing a way to redefine this behavior dynamically, depending of the worksheet

### CODE REVIEW

**Comment by mgcrea** [comment]
Sorry, meanwhile I've rewritten the plugin from the ground up with typesript and leveraging some new sheetjs functions to reduce footprint. Any chance you could rebase your work against the updated master? Thanks!

**Comment by vied12** [comment]
@mgcrea nice job with the rewriting !

Here is my original PR rebased

**Comment by mgcrea** [comment]
Thanks for the rebase, merged, will push a new release today.

**Comment by puchm** [comment]
Hi, I'd like to propose passing the name of the sheet to the function as well. I have not found a way to find out the name from the `xlsx.Worksheet`. As far as I can see it would simply require adding the second parameter and we would still keep it backwards compatible.

**Pull request merged**
